rpc:
    listen: "0.0.0.0:1986"
web: 
    addrs: 
      - "127.0.0.1:1985"
    timeout: 300 
    interval: 60 #get strategy interval
smtp: 
    addr: "mail.addr:25"
    username: "mail@mail.com"
    password: ""
    from: "mail@mail.com"
worker: 
    sms: 10  #send sms concurrency
    mail: 50 #send mail concurrency
# remain: 30
